Ansible error code:


failed: [bravo1]
(item=green.local) => 
{"ansible_loop_var": "item", "changed": false, "checksum": "8941786ff169e92ea883b5f7ce18de6f2cfc3751", 
"exit_status": 1, "item": {"hosts": [{"aliases": ["www"], "ip": "172.16.1.66", "name": "bravo1"},
{"ip": "172.16.1.67", "name": "charlie1"}], "name": "green.local", 
"name_servers": ["ns1.green.local", "ns2.green.local"], 
"networks": ["172.16"]}, "msg": "failed to validate", 
"stderr": "loading \"green.local\" from \"/home/vagrant/.ansible/tmp/ansible-tmp-1570278429.9900386-261274504600025/source\" 
class \"IN\"\n", "stderr_lines": ["loading \"green.local\" from \"/home/vagrant/.ansible/tmp/ansible-tmp-1570278429.9900386-261274504600025/source\" 
class \"IN\""], 
"stdout": "zone green.local/IN: NS 'ns1.green.local.green.local' has no address records (A or AAAA)\n
zone green.local/IN: NS 'ns2.green.local.green.local' has no address records (A or AAAA)\n
zone green.local/IN: not loaded due to errors.\n", 
"stdout_lines": ["zone green.local/IN: NS 'ns1.green.local.green.local' has no address records (A or AAAA)", 
"zone green.local/IN: NS 'ns2.green.local.green.local' has no address records (A or AAAA)", "zone green.local/IN: not loaded due to errors."]}

Mogelijke oorzaak:


Handelingen uitgevoerd:
Bij servers.yml configuratie toegevoegd.
Bravo1 en Charlie1 als hostnames
Ns1 en ns2 ingesteld bij DNS configuratie.